#!/bin/bash
CURRENT_DATE=`date +%Y%m%d%H%M%S`
if [ $# -ne 1 ]
then
   echo "usage:$0 analysisVersion"
   exit 1
fi

ANALYSIS_VERSION=$1

echo 'change jdk to 1.8'

export JAVA_HOME=/data/install/jdk8
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export PATH=$JAVA_HOME/bin:$PATH
java -version


echo 'mvn version :'
mvn -version

WORK_DIR=/data/workspace/groundpush-framework
cd $WORK_DIR
ls -l

mvn clean package

ANALYSIS_JAR_DIR=$WORK_DIR/groundpush-analysis/target/groundpush-analysis-$ANALYSIS_VERSION.jar

REMOTE_ANALYSIS_JAR_DIR=/analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION.jar

START_ANALYSIS_SHELL_DIR=/groundpush/deploy-shell/startAnalysis

echo '---------------------------------------------------------------------'
echo 'ANALYSIS_VERSION: '$ANALYSIS_VERSION
echo 'WORK_DIR: '$WORK_DIR
echo 'ANALYSIS_JAR_DIR: '$ANALYSIS_JAR_DIR
echo 'REMOTE_ANALYSIS_JAR: '$REMOTE_ANALYSIS_JAR
echo 'START_ANALYSIS_SHELL_JAR: '$START_ANALYSIS_SHELL_JAR
echo "BACK UP: ssh root@60.205.177.128  mv /analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION.jar /analysis_deploy/groundpush-analysis-$ANALYSIS_VERSION-$CURRENT_DATE.jar "
echo "COPY JAR:  scp $ANALYSIS_JAR_DIR root@60.205.177.128:$REMOTE_ANALYSIS_JAR_DIR "
echo "CALL BACK startApp: ssh root@60.205.177.128  $START_ANALYSIS_SHELL_DIR $ANALYSIS_VERSION "
echo '---------------------------------------------------------------------'

echo -e "\033[41;37m is deploy analysis for product: \033[0m"
prod="null"
read prod
sleep 1
if [ $prod != "product" ]; then
exit 0
fi

ssh root@60.205.177.128 " mv /analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION.jar /analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION-$CURRENT_DATE.jar "

scp $ANALYSIS_JAR_DIR root@60.205.177.128:$REMOTE_ANALYSIS_JAR_DIR
ssh root@60.205.177.128 " $START_ANALYSIS_SHELL_DIR $ANALYSIS_VERSION "



