#!/bin/bash
CURRENT_DATE=`date +%Y%m%d%H%M%S`
if [ $# -ne 1 ]
then
   echo "usage:$0 webVersion"
   exit 1
fi

WEB_VERSION=$1

WORK_DIR=/data/workspace/groundpush-framework
cd $WORK_DIR
ls -l

mvn clean package

WEB_JAR_DIR=$WORK_DIR/groundpush-web/target/groundpush-web-$WEB_VERSION.jar

REMOTE_WEB_JAR_DIR=/web-deploy/groundpush-web-$WEB_VERSION.jar

START_WEB_SHELL_DIR=/groundpush/deploy-shell/startWeb

echo '---------------------------------------------------------------------'
echo 'WEB_VERSION: '$WEB_VERSION
echo 'WORK_DIR: '$WORK_DIR
echo 'WEB_JAR_DIR: '$WEB_JAR_DIR
echo 'REMOTE_WEB_JAR_DIR: '$REMOTE_WEB_JAR_DIR
echo 'START_WEB_SHELL_DIR: '$START_WEB_SHELL_DIR
echo "BACK UP : ssh root@60.205.177.128  mv /web-deploy/groundpush-web-$WEB_VERSION.jar /web-deploy/groundpush-web-$WEB_VERSION-$CURRENT_DATE.jar "
echo "COPY JAR: $WEB_JAR_DIR root@60.205.177.128:$REMOTE_WEB_JAR_DIR "
echo "CALL BACK startWeb: ssh root@60.205.177.128  $START_WEB_SHELL_DIR $APP_VERSION  "
echo '---------------------------------------------------------------------'

echo -e "\033[41;37m is deploy web for product: \033[0m"
prod="null"
read prod
sleep 1
if [ $prod != "product" ]; then
exit 0
fi

ssh root@60.205.177.128 " mv /web-deploy/groundpush-web-$WEB_VERSION.jar /web-deploy/groundpush-web-$WEB_VERSION-$CURRENT_DATE.jar "

scp $WEB_JAR_DIR root@60.205.177.128:$REMOTE_WEB_JAR_DIR
ssh root@60.205.177.128 " $START_WEB_SHELL_DIR $WEB_VERSION "



