spring:
  thymeleaf:
    cache: false
  datasource:
    name: druid_source
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.2.172.227:3306/groundpush?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: groundpush
    password: groundpush
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: GroundPushHikariCP-Analysis
      max-lifetime: 900000
      connection-timeout: 15000

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    type-aliases-package=com: com.groundpush.model

logging:
  level:
    com.groundpush.analysis.mapper: DEBUG

# 渠道数据映射内部规则格式为：{key:1,value:'人员编号'},{key:2,value:'产生时间'},{key:3,value:'是否有效'},{key:4,value:'失败原因'}
groundpush:
  channel:
    path: /data/doc
    mapping.filed: uniqueCode,produceTime,isEffective,failureResult
  virt.user.id: 5