spring:
  thymeleaf:
    cache: false
  datasource:
    name: druid_source
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.2.172.227:3306/groundpush?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: groundpush
    password: groundpush
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 2
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
      validation-query: select 'x'
      filter: stat,wall

pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

groundpush:
  channel:
    path: /tmp/channel