#!/bin/bash

echo 'calback startApp'

CURRENT_DATE=`date +%Y%m%d%H%M%S`

if [ $# -ne 1 ]
then
   echo "usage:$0 appVersion"
   exit 1
fi

APP_VERSION=$1
APP_PORT=8180
APP_LOG_DIR=/var/log/app/start-$APP_PORT-groundpush-$CURRENT_DATE.log
pid=$(netstat -nlp | grep :$APP_PORT | awk '{print $7}' | awk -F"/" '{print $1}');

if [ -n  "$pid" ]; then
    kill  -9  $pid;
fi

echo '-----------------------------------------------------------------'
echo "app_version:$APP_VERSION"
echo "app_port:$APP_PORT"
echo "/app-deploy/groundpush-app-$APP_VERSION.jar spring.profiles.active=prod server.port=$APP_PORT  /var/log/app/start-$APP_PORT-groundpush-$CURRENT_DATE.log "
echo "pid:$pid"
echo '-----------------------------------------------------------------'


echo '##############################startApp######################################################'

exec  java -jar /app-deploy/groundpush-app-$APP_VERSION.jar --spring.profiles.active=prod --server.port=$APP_PORT | head -n 1000 >> $APP_LOG_DIR 2>&1 &
sleep 3
tail -f $APP_LOG_DIR

