#!/bin/bash

echo 'calback startAnalysis'

CURRENT_DATE=`date +%Y%m%d%H%M%S`

if [ $# -ne 1 ]
then
   echo "usage:$0 analysisVersion"
   exit 1
fi

ANALYSIS_VERSION=$1
ANALYSIS_PORT=8380
ANALYSIS_LOG_DIR=/var/log/analysis/start-$ANALYSIS_PORT-groundpush-$CURRENT_DATE.log
pid=$(netstat -nlp | grep :$ANALYSIS_PORT | awk '{print $7}' | awk -F"/" '{print $1}');

if [ -n  "$pid" ]; then
    kill  -9  $pid;
fi

echo '-----------------------------------------------------------------'
echo "analysis_version:$ANALYSIS_VERSION"
echo "analysis_port:$ANALYSIS_PORT"
echo "/analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION.jar spring.profiles.active=prod server.port=$ANALYSIS_PORT $ANALYSIS_LOG_DIR "
echo "pid:$pid"
echo '-----------------------------------------------------------------'


echo '##############################startApp######################################################'

exec  java -jar /analysis-deploy/groundpush-analysis-$ANALYSIS_VERSION.jar --spring.profiles.active=prod --server.port=$ANALYSIS_PORT | head -n 1000 >> $ANALYSIS_LOG_DIR 2>&1 &
sleep 3
tail -f $ANALYSIS_LOG_DIR

